CREATE TABLE COMPONENTE(
 ID SERIAL NOT NULL,
 NOME VARCHAR(250) NOT NULL,
 TIPO VARCHAR(250) NOT NULL,
 DATA_LANCAMENTO DATE,

 CONSTRAINT PK_COMPONENTE_ID PRIMARY KEY (ID)
);

CREATE TABLE USUARIO(
 ID SERIAL NOT NULL,
 NOME VARCHAR(250) NOT NULL,
 EMAIL VARCHAR(250) NOT NULL,
 PASSWORD VARCHAR(250) NOT NULL,

 CONSTRAINT PK_USUARIO_ID PRIMARY KEY (ID)
);

CREATE TABLE BUILD(
 ID SERIAL NOT NULL,
 ID_USUARIO INTEGER NOT NULL,

 CONSTRAINT PK_BUILD_ID PRIMARY KEY (ID),
 CONSTRAINT FK_BUILD_CLIENTE FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE COMPONENTE_BUILD(
 ID SERIAL NOT NULL,
 ID_COMPONENTE INTEGER NOT NULL,
 ID_BUILD INTEGER NOT NULL,
 DATA_CRIACAO DATE NOT NULL,

 CONSTRAINT PK_COMPONENTE_BUILD_ID PRIMARY KEY (ID),
 CONSTRAINT FK_COMPONENTE_BUILD_COMPONENTE FOREIGN KEY(ID_COMPONENTE) REFERENCES COMPONENTE(ID),
 CONSTRAINT FK_COMPONENTE_BUILD_BUILD FOREIGN KEY(ID_BUILD) REFERENCES BUILD(ID)
);
